### PR TITLE
fixed GetDialogDimensions when Frame is null

### LINKED ISSUE #624: NullReference Exception running Console Gui
Running develop on a Terminology console in Ubuntu `rdmp gui`

```
2021-11-02 12:15:00.2454 ERROR Object reference not set to an instance of an object. . 
2021-11-02 12:15:00.2454 INFO Fatal error occurred so returning -1 . System.NullReferenceException: Object reference not set to an instance of an object.
   at Rdmp.Core.CommandLine.Gui.ConsoleGuiActivator.GetDialogDimensions(Int32& w, Int32& h) in /home/thomas/RDMP/Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs:line 100
   at Rdmp.Core.CommandLine.Gui.ConsoleGuiActivator.ShowException(String errorText, Exception exception) in /home/thomas/RDMP/Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs:line 306
   at Rdmp.Core.CommandExecution.BasicActivateItems.GetChildProvider() in /home/thomas/RDMP/Rdmp.Core/CommandExecution/BasicActivateItems.cs:line 113
   at Rdmp.Core.CommandExecution.BasicActivateItems..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ICheckNotifier globalErrorCheckNotifier) in /home/thomas/RDMP/Rdmp.Core/CommandExecution/BasicActivateItems.cs:line 92
   at Rdmp.Core.CommandLine.Gui.ConsoleGuiActivator..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ICheckNotifier globalErrorCheckNotifier) in /home/thomas/RDMP/Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs:line 38
   at Rdmp.Core.CommandLine.Gui.ConsoleGuiRunner.Run(IRDMPPlatformRepositoryServiceLocator repositoryLocator, IDataLoadEventListener listener, ICheckNotifier checkNotifier, GracefulCancellationToken token) in /home/thomas/RDMP/Tools/rdmp/CommandLine/Gui/ConsoleGuiRunner.cs:line 35
   at Rdmp.Core.Program.Run(RDMPCommandLineOptions opts) in /home/thomas/RDMP/Tools/rdmp/Program.cs:line 218
   at Rdmp.Core.Program.<>c.<HandleArguments>b__4_9(ConsoleGuiOptions opts) in /home/thomas/RDMP/Tools/rdmp/Program.cs:line 114
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 parsedFunc9, Func`2 parsedFunc10, Func`2 parsedFunc11, Func`2 notParsedFunc)
   at Rdmp.Core.Program.HandleArguments(String[] args, Logger logger) in /home/thomas/RDMP/Tools/rdmp/Program.cs:line 89
```

This seems to happen when there are errors before startup has completed in console.  E.g. when the data export connection string is wrong.  In this case there is no top Frame

### PR DESCRIPTION
**Pull request by tznind**
Fixes #624

### CODE REVIEW

File: Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs [hunk 1]
```diff
@@ -97,8 +97,11 @@ public override bool YesNo(string text, string caption, out bool chosen)
 
         private void GetDialogDimensions(out int w, out int h)
         {
-            w = Math.Min(80, Application.Top.Frame.Width - 4);
-            h = Math.Min(20, Application.Top.Frame.Height - 2);
+            w = Application.Top?.Frame.Width??0;
```
Comment (jas88) [inline Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs:100]: Looks like this checks if Top is null, but not Frame?

Comment (tznind) [reply Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs:100]: I think Frame is a `struct`

**Review by jas88 — APPROVED** [review]
